# ---- Base image: AWS publishes one per Python minor version ----
FROM public.ecr.aws/lambda/python:3.12

# ---- Install Python depsawscl ----
COPY requirements.txt .
RUN pip install -r requirements.txt

# ---- Copy source code into the image ----
COPY . .

# ---- Tell Lambda which handler to execute ----
CMD ["lambda_handler.handler"]
